export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_DEPOSITS = 'GET_DEPOSITS';
export const GET_WITHDRAWAL = 'GET_WITHDRAWAL';
export const CLEAR_CURRENT_TRANSACTIONS = 'CLEAR_CURRENT_TRANSACTIONS';
export const GET_BALANCE = 'GET_BALANCE';
export const FUND_ACCOUNT = 'FUND_ACCOUNT';
export const POST_DEPOSIT = 'POST_DEPOSITS';
export const POST_WITHDRAWAL = 'POST_WITHDRAWAL';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING';